In [1]:
import os
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
os.chdir(r"D:\Karan\ML")

In [5]:
data=pd.read_csv("bank_xgb.csv")

In [6]:
data.head()

Unnamed: 0  age  balance  duration  campaign  previous  recent_pdays  \
0           0   59     2343      1042         1         0        0.0001   
1           1   56       45      1467         1         0        0.0001   
2           2   41     1270      1389         1         0        0.0001   
3           3   55     2476       579         1         0        0.0001   
4           4   54      184       673         2         0        0.0001   

   deposit_cat  job_Pink-collar  job_White-collar  ...  marital_married  \
0            1                0                 1  ...                1   
1            1                0                 1  ...                1   
2            1                0                 0  ...                1   
3            1                1                 0  ...                1   
4            1                0                 1  ...                1   

   marital_single  education_secondary  education_tertiary  education_unknown  \
0               0                    1                   0                  0   
1               0                    1                   0                  0   
2               0                    1                   0                  0   
3               0                    1                   0                  0   
4               0                    0                   1                  0   

   default_yes  housing_yes  loan_yes  poutcome_others  poutcome_success  
0            0            1         0                1                 0  
1            0            0         0                1                 0  
2            0            1         0                1                 0  
3            0            1         0                1                 0  
4            0            0         0                1                 0  

[5 rows x 23 columns]

In [7]:
data.columns

Index(['Unnamed: 0', 'age', 'balance', 'duration', 'campaign', 'previous',
       'recent_pdays', 'deposit_cat', 'job_Pink-collar', 'job_White-collar',
       'job_blue-collar', 'job_self-depend', 'job_technician',
       'marital_married', 'marital_single', 'education_secondary',
       'education_tertiary', 'education_unknown', 'default_yes', 'housing_yes',
       'loan_yes', 'poutcome_others', 'poutcome_success'],
      dtype='object')

In [8]:
data.drop(["Unnamed: 0"], axis=1, inplace=True)

In [10]:
data.head()

age  balance  duration  campaign  previous  recent_pdays  deposit_cat  \
0   59     2343      1042         1         0        0.0001            1   
1   56       45      1467         1         0        0.0001            1   
2   41     1270      1389         1         0        0.0001            1   
3   55     2476       579         1         0        0.0001            1   
4   54      184       673         2         0        0.0001            1   

   job_Pink-collar  job_White-collar  job_blue-collar  ...  marital_married  \
0                0                 1                0  ...                1   
1                0                 1                0  ...                1   
2                0                 0                0  ...                1   
3                1                 0                0  ...                1   
4                0                 1                0  ...                1   

   marital_single  education_secondary  education_tertiary  education_unknown  \
0               0                    1                   0                  0   
1               0                    1                   0                  0   
2               0                    1                   0                  0   
3               0                    1                   0                  0   
4               0                    0                   1                  0   

   default_yes  housing_yes  loan_yes  poutcome_others  poutcome_success  
0            0            1         0                1                 0  
1            0            0         0                1                 0  
2            0            1         0                1                 0  
3            0            1         0                1                 0  
4            0            0         0                1                 0  

[5 rows x 22 columns]

In [11]:
data.columns

Index(['age', 'balance', 'duration', 'campaign', 'previous', 'recent_pdays',
       'deposit_cat', 'job_Pink-collar', 'job_White-collar', 'job_blue-collar',
       'job_self-depend', 'job_technician', 'marital_married',
       'marital_single', 'education_secondary', 'education_tertiary',
       'education_unknown', 'default_yes', 'housing_yes', 'loan_yes',
       'poutcome_others', 'poutcome_success'],
      dtype='object')

In [12]:
y=data["deposit_cat"]
X=data.drop(["deposit_cat"], axis=1)

In [23]:
import statsmodels.formula.api as sm
gh=sm.logit("deposit_cat ~ age+balance+duration+balance+recent_pdays+housing_yes+poutcome_success",data).fit()

Optimization terminated successfully.
         Current function value: 0.479247
         Iterations 7


In [24]:
print(gh.summary())

                           Logit Regression Results                           
Dep. Variable:            deposit_cat   No. Observations:                11162
Model:                          Logit   Df Residuals:                    11155
Method:                           MLE   Df Model:                            6
Date:                Sat, 26 Feb 2022   Pseudo R-squ.:                  0.3072
Time:                        15:26:30   Log-Likelihood:                -5349.3
converged:                       True   LL-Null:                       -7721.6
Covariance Type:            nonrobust   LLR p-value:                     0.000
                       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept           -1.3974      0.097    -14.457      0.000      -1.587      -1.208
age                 -0.0037      0.002     -1.818      0.069      -0.008       0.000
balance           4.777e-05 

In [26]:
# pip install abcXYZ
import abcXYZ
abcXYZ.ab(4,6)

10

In [13]:
from sklearn.model_selection import train_test_split, GridSearchCV

In [14]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn import metrics
from sklearn import svm 

In [15]:
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=.2, random_state=88)

In [16]:
sc=StandardScaler()
sc_fit=sc.fit(X_train)

In [17]:
X_train_sc=sc_fit.transform(X_train)
X_test_sc=sc_fit.transform(X_test)

In [15]:
# pd.DataFrame(X_train_sc, columns=X_train.columns)

In [16]:
# X_train_sc

In [18]:
X_train_sc_df=pd.DataFrame(X_train_sc, columns=X_train.columns)
X_test_sc_df=pd.DataFrame(X_test_sc, columns=X_test.columns)

In [20]:
# X_test_sc_df

In [21]:
help(svm)

Help on package sklearn.svm in sklearn:

NAME
    sklearn.svm - The :mod:`sklearn.svm` module includes Support Vector Machine algorithms.

PACKAGE CONTENTS
    _base
    _bounds
    _classes
    _liblinear
    _libsvm
    _libsvm_sparse
    _newrand
    setup
    tests (package)

CLASSES
    sklearn.base.BaseEstimator(builtins.object)
        sklearn.svm._classes.LinearSVC(sklearn.linear_model._base.LinearClassifierMixin, sklearn.linear_model._base.SparseCoefMixin, sklearn.base.BaseEstimator)
    sklearn.base.OutlierMixin(builtins.object)
        sklearn.svm._classes.OneClassSVM(sklearn.base.OutlierMixin, sklearn.svm._base.BaseLibSVM)
    sklearn.base.RegressorMixin(builtins.object)
        sklearn.svm._classes.LinearSVR(sklearn.base.RegressorMixin, sklearn.linear_model._base.LinearModel)
        sklearn.svm._classes.NuSVR(sklearn.base.RegressorMixin, sklearn.svm._base.BaseLibSVM)
        sklearn.svm._classes.SVR(sklearn.base.RegressorMixin, sklearn.svm._base.BaseLibSVM)
    sklearn.li

In [25]:
sv1=svm.SVC()
# help(sv1)
import time

In [26]:

st=time.time()
sv1.fit(X_train_sc_df, y_train)
print("Train score :", sv1.score(X_train_sc_df, y_train))
print("Test score :", sv1.score(X_test_sc_df, y_test))
et=time.time()
print("time Taken", et-st, "sec")

Train score : 0.8214805689326913
Test score : 0.8316166592028661
time Taken 8.171918153762817 sec


In [28]:
sv1.predict(X_train_sc_df)

array([1, 1, 0, ..., 1, 1, 0], dtype=int64)

In [29]:
sv1.predict_proba(X_train_sc_df)

AttributeError: predict_proba is not available when  probability=False

In [30]:
sv1=svm.SVC(probability=True)
st=time.time()
sv1.fit(X_train_sc_df, y_train)
print("Train score :", sv1.score(X_train_sc_df, y_train))
print("Test score :", sv1.score(X_test_sc_df, y_test))
et=time.time()
print("time Taken", et-st, "sec")

Train score : 0.8214805689326913
Test score : 0.8316166592028661
time Taken 20.588422775268555 sec


In [31]:
sv2=svm.SVC(kernel='linear')
st=time.time()
sv2.fit(X_train_sc_df, y_train)
print("Train score :", sv2.score(X_train_sc_df, y_train))
print("Test score :", sv2.score(X_test_sc_df, y_test))
et=time.time()
print("time Taken", et-st, "sec")

Train score : 0.7905700526374734
Test score : 0.8110165696372593
time Taken 5.943622350692749 sec


In [32]:
st=time.time()

sv2=svm.SVC(kernel="linear", C=10)
sv2.fit(X_train_sc_df, y_train)
print("Train score :", sv2.score(X_train_sc_df, y_train))
print("Test score :", sv2.score(X_test_sc_df, y_test))
et=time.time()
print("Time Taken", et-st, "sec")


Train score : 0.7911300257587636
Test score : 0.8110165696372593
Time Taken 13.103582382202148 sec


In [33]:
st=time.time()
sv2=svm.SVC(kernel="linear", C=10, probability=True)
sv2.fit(X_train_sc_df, y_train)
print("Train score :", sv2.score(X_train_sc_df, y_train))
print("Test score :", sv2.score(X_test_sc_df, y_test))
et=time.time()
print("Time Taken", et-st, "sec")


Train score : 0.7911300257587636
Test score : 0.8110165696372593
Time Taken 63.15420079231262 sec


In [ ]:
# sv2.predict()

In [34]:
st=time.time()
sv2=svm.SVC(kernel="poly", degree=2)
sv2.fit(X_train_sc_df, y_train)
print("Train score :", sv2.score(X_train_sc_df, y_train))
print("Test score :", sv2.score(X_test_sc_df, y_test))
et=time.time()
print("Time Taken", et-st, "sec")

Train score : 0.7331168103931012
Test score : 0.729511867442902
Time Taken 7.298057794570923 sec


In [35]:
st=time.time()
sv2=svm.SVC(kernel="poly", degree=3)
sv2.fit(X_train_sc_df, y_train)
print("Train score :", sv2.score(X_train_sc_df, y_train))
print("Test score :", sv2.score(X_test_sc_df, y_test))
et=time.time()
print("Time Taken", et-st, "sec")

Train score : 0.8163288162168216
Test score : 0.8114643976712942
Time Taken 6.864281415939331 sec


In [36]:
sv2=svm.SVC(kernel="poly", degree=3, probability=True)
sv2.fit(X_train_sc_df, y_train)
print("Train score :", sv2.score(X_train_sc_df, y_train))
print("Test score :", sv2.score(X_test_sc_df, y_test))


Train score : 0.8163288162168216
Test score : 0.8114643976712942


In [46]:
sv2.predict(X_train_sc_df)

array([1, 1, 0, ..., 1, 1, 0], dtype=int64)

In [47]:
sv2.predict_proba(X_train_sc_df)

array([[0.21642325, 0.78357675],
       [0.44388339, 0.55611661],
       [0.84961766, 0.15038234],
       ...,
       [0.13568074, 0.86431926],
       [0.48716612, 0.51283388],
       [0.69160218, 0.30839782]])

In [37]:
dfhh.to_csv(r"D:\Training\Imarticus\PGA\PGA15\week10\profile.csv")

In [49]:
def profile_decile(X,y,trained_model):
    X_1=X.copy()
    y_1=y.copy()
    y_pred1=trained_model.predict(X_1)
    X_1["Prob_Event"]=trained_model.predict_proba(X_1)[:,1]
    X_1["Y_actual"]=y_1
    X_1["Y_pred"]=y_pred1
    X_1["Rank"]=pd.qcut(X_1["Prob_Event"], 10, labels=np.arange(0,10,1))
    X_1["numb"]=10
    X_1["Decile"]=X_1["numb"]-X_1["Rank"].astype("int")
    
    profile=pd.DataFrame(X_1.groupby("Decile") \
                        .apply(lambda x: pd.Series({
        'min_score'   : x["Prob_Event"].min(),
        'max_score'   : x["Prob_Event"].max(),
        'Event'       : x["Y_actual"].sum(),
        'Non_event'   : x["Y_actual"].count()-x["Y_actual"].sum(),
        'Total'       : x["Y_actual"].count() })))
    return profile

In [50]:
profile_decile(X_train_sc_df,y_train,sv2) 

min_score  max_score  Event  Non_event  Total
Decile                                                  
1       9.055004e-01   1.000000  420.0      283.0  703.0
2       8.135451e-01   0.905443  432.0      271.0  703.0
3       7.189825e-01   0.813340  426.0      306.0  732.0
4       5.635493e-01   0.718858  402.0      290.0  692.0
5       4.126315e-01   0.563487  397.0      317.0  714.0
6       2.940495e-01   0.412133  425.0      295.0  720.0
7       2.163789e-01   0.293814  434.0      308.0  742.0
8       1.736204e-01   0.216379  426.0      281.0  707.0
9       1.250898e-01   0.173610  444.0      276.0  720.0
10      1.000000e-07   0.125011  418.0      307.0  725.0

In [37]:
from sklearn.model_selection import RandomizedSearchCV

In [38]:
3*3*3*6*10

1620

In [39]:
params={"kernel":['linear', 'poly', 'rbf'],
       "degree":[2,3,4],
       "gamma":[0.1, 1,.001],
       "C":[0.001, 0.01, 0.1, 1, 10, 100]
       }
sv=svm.SVC()
svm_rs=RandomizedSearchCV(sv, params, cv=10, n_jobs=-1, verbose=True)
svm_rs.fit(X_train_sc_df, y_train)

Fitting 10 folds for each of 10 candidates, totalling 100 fits


RandomizedSearchCV(cv=10, estimator=SVC(), n_jobs=-1,
                   param_distributions={'C': [0.001, 0.01, 0.1, 1, 10, 100],
                                        'degree': [2, 3, 4],
                                        'gamma': [0.1, 1, 0.001],
                                        'kernel': ['linear', 'poly', 'rbf']},
                   verbose=True)

In [40]:
svm_rs.best_params_

{'kernel': 'rbf', 'gamma': 0.1, 'degree': 3, 'C': 1}

In [41]:
params={"kernel":['linear', 'poly', 'rbf'],
       "degree":[2,3, 4],
       "gamma":[0.1,.01],
       "C":[10, 100]
       }
sv=svm.SVC()

sv_gs=GridSearchCV(sv, param_grid=params, cv=5, n_jobs=-1, verbose=True)
sv_gs.fit(X_train_sc_df, y_train)


Fitting 5 folds for each of 36 candidates, totalling 180 fits


GridSearchCV(cv=5, estimator=SVC(), n_jobs=-1,
             param_grid={'C': [10, 100], 'degree': [2, 3, 4],
                         'gamma': [0.1, 0.01],
                         'kernel': ['linear', 'poly', 'rbf']},
             verbose=True)

In [42]:
sv_gs.best_params_

{'C': 10, 'degree': 2, 'gamma': 0.01, 'kernel': 'rbf'}

In [43]:
sv2=svm.SVC(kernel="rbf", degree=2,gamma=0.01, C=10, probability=True)
sv2.fit(X_train_sc_df, y_train)
print("Train score :", sv2.score(X_train_sc_df, y_train))
print("Test score :", sv2.score(X_test_sc_df, y_test))

Train score : 0.814536902228693
Test score : 0.8307210031347962
